# `Generator` 函数的概念和应用

##  1. 简介

## 基本概念

1. **从语法**上看 `Generator` 函数可以看成是一个状态机，内部封装了多个状态。

2. **从执行机制**上看，`Generator` 函数会返回一个遍历器对象，可以依次遍历函数内部的每一个状态。

3. **从代码形式**上看，`Generator` 函数就是一个普通函数，但是有两个特征。

   1. `function` 关键字和函数名之间有一个 `*` 号。
   2. 函数体内部使用 `yield` 表达式。

   ```javascript
   function* helloWorldGenerator() {
     yield 'hello';
     yield 'world';
     return 'ending';
   }
   
   var hw = helloWorldGenerator();
   ```

   上面代码定义了一个 Generator 函数`helloWorldGenerator`，它内部有两个`yield`表达式（`hello`和`world`），即该函数有三个状态：`hello，world` 和 `return` 语句（结束执行）。

4. **从调用方式**看，Generator函数的调用方式和普通函数一样，但是调用Generator函数之后，***函数并不执行***，而是返回一个指向内部状态的指针对象，也就是遍历器对象（Iterator Object）。

5. 调用 `Generator` 函数拿到遍历器对象之后，下一步就是调用遍历器对象的 `next` 方法，使得指针移向下一个状态。也就是说，每次调用`next`方法，内部指针就从函数头部或上一次停下来的地方开始执行，直到遇到下一个`yield`表达式（或`return`语句）为止。换言之，Generator 函数是分段执行的，`yield`表达式是暂停执行的标记，而`next`方法可以恢复执行。

## `yield` 表达式

> 由于 Generator 函数返回的遍历器对象，只有调用next方法才会遍历下一个内部状态，所以其实提供了一种可以暂停执行的函数。yield表达式就是暂停标志。
> 1. `yield` 表达式只能用在 `Generator` 函数内部，用在普通函数内部会报错。
>
> 2. `yield`表达式如果用在另一个表达式之中，必须放在圆括号里面。
>
>    ```js
>    function* demo() {
>      console.log('Hello' + yield); // SyntaxError
>      console.log('Hello' + yield 123); // SyntaxError
>    
>      console.log('Hello' + (yield)); // OK
>      console.log('Hello' + (yield 123)); // OK
>    }
>    ```
>
> 3. 

## `next` 方法的参数

`yield`表达式本身没有返回值，或者说总是返回`undefined`。`next`方法可以带一个参数，***该参数就会被当作上一个`yield`表达式的返回值。***

看一个例子：

```javascript
function* foo(x) {
  var y = 2 * (yield (x + 1));
  var z = yield (y / 3);
  return (x + y + z);
}

var a = foo(5);
a.next() // Object{value:6, done:false}
a.next() // Object{value:NaN, done:false}
a.next() // Object{value:NaN, done:true}

var b = foo(5);
b.next() // { value:6, done:false }
b.next(12) // { value:8, done:false }
b.next(13) // { value:42, done:true }
```

上面代码中，第二次运行`next`方法的时候不带参数，导致 y 的值等于`2 * undefined`（即`NaN`），除以 3 以后还是`NaN`，因此返回对象的`value`属性也等于`NaN`。第三次运行`Next`方法的时候不带参数，所以`z`等于`undefined`，返回对象的`value`属性等于`5 + NaN + undefined`，即`NaN`。

如果向`next`方法提供参数，返回结果就完全不一样了。上面代码第一次调用`b`的`next`方法时，返回`x+1`的值`6`；第二次调用`next`方法，将上一次`yield`表达式的值设为`12`，因此`y`等于`24`，返回`y / 3`的值`8`；第三次调用`next`方法，将上一次`yield`表达式的值设为`13`，因此`z`等于`13`，这时`x`等于`5`，`y`等于`24`，所以`return`语句的值等于`42`。

注意，由于`next`方法的参数表示上一个`yield`表达式的返回值，所以在第一次使用`next`方法时，传递参数是无效的。V8 引擎直接忽略第一次使用`next`方法时的参数，只有从第二次使用`next`方法开始，参数才是有效的。从语义上讲，第一个`next`方法用来启动遍历器对象，所以不用带有参数。

## for...of 循环

> `for...of`循环可以自动遍历 Generator 函数运行时生成的`Iterator`对象，且此时不再需要调用`next`方法。`for...of` 中定义的变量就是 `yield` 的返回值。

```javascript
function* foo() {
  yield 1;
  yield 2;
  yield 3;
  yield 4;
  yield 5;
  return 6;
}

for (let v of foo()) {
  console.log(v);
}
// 1 2 3 4 5
```

上面代码使用`for...of`循环，依次显示 5 个`yield`表达式的值。这里需要注意，一旦`next`方法的返回对象的`done`属性为`true`，`for...of`循环就会中止，且不包含该返回对象，所以上面代码的`return`语句返回的`6`，不包括在`for...of`循环之中。

## `yield` 表达式

如果在 `Generator` 函数内部，调用另一个 `Generator` 函数。需要在前者的函数体内部，自己手动完成遍历。

```javascript
function* foo() {
  yield 'a';
  yield 'b';
}

function* bar() {
  yield 'x';
  // 手动遍历 foo()
  for (let i of foo()) {
    console.log(i);
  }
  yield 'y';
}

for (let v of bar()){
  console.log(v);
}
// x
// a
// b
// y
```

ES6 提供了`yield*`表达式，作为解决办法，用来在一个 Generator 函数里面执行另一个 Generator 函数。

```javascript
function* bar() {
  yield 'x';
  yield* foo();
  yield 'y';
}

// 等同于
function* bar() {
  yield 'x';
  yield 'a';
  yield 'b';
  yield 'y';
}

// 等同于
function* bar() {
  yield 'x';
  for (let v of foo()) {
    yield v;
  }
  yield 'y';
}

for (let v of bar()){
  console.log(v);
}
// "x"
// "a"
// "b"
// "y"
```

## 对象属性时 `Generator` 函数

如果一个对象的属性是 Generator 函数，可以简写成下面的形式。

```javascript
let obj = {
  * myGeneratorMethod() {
    ···
  }
};
```

上面代码中，`myGeneratorMethod`属性前面有一个星号，表示这个属性是一个 Generator 函数。

它的完整形式如下，与上面的写法是等价的。

```javascript
let obj = {
  myGeneratorMethod: function* () {
    // ···
  }
};
```

## `Generator` 函数中的 `this`

> 具体见：[Generator 函数的this](https://es6.ruanyifeng.com/#docs/generator)


1. `Generator` 函数总是返回一个遍历器，ES6 规定这个遍历器是 `Generator` 函数的实例，也继承了 `Generator` 函数的`prototype`对象上的方法。

2. Generator 函数也不能跟`new`命令一起用，会报错。

   

   ```js
   function* F() {
     yield this.x = 2;
     yield this.y = 3;
   }
   
   new F()
   // TypeError: F is not a constructor
   ```

   > 上面代码中，`new`命令跟构造函数`F`一起使用，结果报错，因为`F`不是构造函数。


## Generator状态机

Generator 是实现状态机的最佳结构。比如，下面的`clock`函数就是一个状态机。

```javascript
var ticking = true;
var clock = function() {
  if (ticking)
    console.log('Tick!');
  else
    console.log('Tock!');
  ticking = !ticking;
}
```

上面代码的`clock`函数一共有两种状态（`Tick`和`Tock`），每运行一次，就改变一次状态。这个函数如果用 Generator 实现，就是下面这样。

```javascript
var clock = function* () {
  while (true) {
    console.log('Tick!');
    yield;
    console.log('Tock!');
    yield;
  }
};
```

上面的 Generator 实现与 ES5 实现对比，可以看到少了用来保存状态的外部变量`ticking`，这样就更简洁，更安全（状态不会被非法篡改）、更符合函数式编程的思想，在写法上也更优雅。Generator 之所以可以不用外部变量保存状态，是因为它本身就包含了一个状态信息，即目前是否处于暂停态。

## 应用

Generator 函数的常规应用主要分为下边的四个场景

（1）[异步操作的同步化表达 §](https://es6.ruanyifeng.com/#docs/generator#（1）异步操作的同步化表达) [⇧](https://es6.ruanyifeng.com/#docs/generator)

（2）[控制流管理 §](https://es6.ruanyifeng.com/#docs/generator#（2）控制流管理) [⇧](https://es6.ruanyifeng.com/#docs/generator)

（3）[部署 Iterator 接口 §](https://es6.ruanyifeng.com/#docs/generator#（3）部署-Iterator-接口) [⇧](https://es6.ruanyifeng.com/#docs/generator)

（4）[作为数据结构 §](https://es6.ruanyifeng.com/#docs/generator#（4）作为数据结构) [⇧](https://es6.ruanyifeng.com/#docs/generator)



# `Promise`

> 涉及面试题：Promise 的特点是什么，分别有什么优缺点？什么是 Promise 链？Promise 构造函数执行和 then 函数执行有什么区别？

1. Promise 的特点
   - 有 `pending, resolved, rejected` 三种状态，从一种状态变为另一种状态之后就不能再改变。
   - 当我们在构造 `Promise` 的时候，构造函数内部的代码是立即执行的
   
2. `Promise` 实现了链式调用，每次调用 `then` 方法之后都会返回一个***全新的 `Promise`***，如果你在 `then` 中 使用了 `return`，那么 `return` 的值会被 `Promise.resolve()` 包装。

3. Promise 的**缺点**是无法被取消。错误需要通过回调函数捕获。

4. 注意，调用`resolve`或`reject`并不会终结 Promise 的参数函数的执行。

   ```javascript
   new Promise((resolve, reject) => {
     resolve(1);
     console.log(2);
   }).then(r => {
     console.log(r);
   });
   // 2
   // 1
   ```

5. 一般来说，调用`resolve`或`reject`以后，Promise 的使命就完成了，后继操作应该放到`then`方法里面，而不应该直接写在`resolve`或`reject`的后面。所以，最好在它们前面加上`return`语句，这样就不会有意外。

   ```js
   new Promise((resolve, reject) => {
     return resolve(1);
     // 后面的语句不会执行
     console.log(2);
   })
   ```

6. 如果 Promise 状态已经变成`resolved`，再抛出错误是无效的。

   ```js
   const promise = new Promise(function(resolve, reject) {
     resolve('ok');
     throw new Error('test');
   });
   promise
     .then(function(value) { console.log(value) })
     .catch(function(error) { console.log(error) });
   // ok
   ```

7. Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个`catch`语句捕获。

   ```js
   new Promise(function(resolve, reject) {
      resolve(1)
   }).then(() => {
       throw new Error(2)
   }).then(() => {
       throw new Error(3)
   }).catch(res => {
       console.log(res)
   })
   
   // catch 会捕获第一个错误，后边的 then 方法会被忽略执行，直接跳转到 catch 方法
   ```

8. 一般来说，***不要在`then()`方法里面定义 Reject 状态的回调函数***（即`then`的第二个参数），总是使用`catch`方法。

9. Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应（这里是指不影响执行外部代码执行）。

   ```javascript
   const someAsyncThing = function() {
     return new Promise(function(resolve, reject) {
       // 下面一行会报错，因为x没有声明
       resolve(x + 2);
     });
   };
   
   someAsyncThing().then(function() {
     console.log('everything is great');
   });
   
   setTimeout(() => { console.log(123) }, 2000);
   // Uncaught (in promise) ReferenceError: x is not defined
   // 123
   /**
   上面代码中，someAsyncThing()函数产生的 Promise 对象，内部有语法错误。浏览器运行到这一行，会打印出错误提示ReferenceError: x is not defined，但是不会退出进程、终止脚本执行，2 秒之后还是会输出123。这就是说，Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。
   /*
   ```

10. `catch()`方法返回的还是一个 Promise 对象，因此后面还可以接着调用`then()`方法。

    ```javascript
    const someAsyncThing = function() {
      return new Promise(function(resolve, reject) {
        // 下面一行会报错，因为x没有声明
        resolve(x + 2);
      });
    };
    
    someAsyncThing()
    .catch(function(error) {
      console.log('oh no', error);
    })
    .then(function() {
      console.log('carry on');
    });
    // oh no [ReferenceError: x is not defined]
    // carry on
    ```

    上面代码运行完`catch()`方法指定的回调函数，会接着运行后面那个`then()`方法指定的回调函数。如果没有报错，则会跳过`catch()`方法。

### `Promise.all`

> `Promise.all()`方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
>
> ```javascript
> const p = Promise.all([p1, p2, p3]);
> ```
>
> 上面代码中，`Promise.all()`方法接受一个数组作为参数，`p1`、`p2`、`p3`都是 Promise 实例，如果不是，就会先调用下面讲到的`Promise.resolve`方法，将参数转为 Promise 实例，再进一步处理。另外，`Promise.all()`方法的参数可以不是数组，但必须具有 Iterator 接口，且返回的每个成员都是 Promise 实例。
>
> `p`的状态由`p1`、`p2`、`p3`决定，分成两种情况。
>
> （1）只有`p1`、`p2`、`p3`的状态都变成`fulfilled`，`p`的状态才会变成`fulfilled`，此时`p1`、`p2`、`p3`的返回值组成一个数组，传递给`p`的回调函数。
>
> （2）只要`p1`、`p2`、`p3`之中有一个被`rejected`，`p`的状态就变成`rejected`，此时第一个被`reject`的实例的返回值，会传递给`p`的回调函数。

- 如果作为参数的 Promise 实例，自己定义了`catch`方法，那么它一旦被`rejected`，并不会触发`Promise.all()`的`catch`方法。否则会触发`Promise.all`的 catch 方法。

### `Promise.race`

`Promise.race()`方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。

```javascript
const p = Promise.race([p1, p2, p3]);
```

上面代码中，只要`p1`、`p2`、`p3`之中有一个实例率先改变状态，`p`的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给`p`的回调函数。

# `async & await`

> 涉及面试题：async 及 await 的特点，它们的优点和缺点分别是什么？await 原理是什么？

